### ISSUE TITLE
Multimedia and Quoting

### ISSUE THREAD

**Issue by n4ch0m4n** [ventureoo/jabagram#1]
When we write a text from Telegram by "quoting" a message from xmpp, it travels with the quote to xmpp. This is ok!

On the other hand, when from Telegram sending a multimedia by "quoting" a message from xmpp, it does NOT travel with the quote to xmpp, only the multimedia arrives without the quote.

thanks!

**Comment by ventureoo** [comment]
Unfortunately it's XMPP problem by design that you can't add any additional message text to attachments/files. The only solution I can think of is to separate sending multimedia and quotes into separate messages.

**Comment by ventureoo** [comment]
Should be fixed with https://github.com/ventureoo/jabagram/commit/f86b3a785f4e20954f8ee99b5c1e48b6ec585071. Thanks for reporting.

**Comment by n4ch0m4n** [comment]
> Should be fixed with [f86b3a7](https://github.com/ventureoo/jabagram/commit/f86b3a785f4e20954f8ee99b5c1e48b6ec585071). Thanks for reporting.

thanks man!!! it´s ok now!
