### ISSUE TITLE
TelegramAPI - Cannot connect

### ISSUE THREAD

**Issue by n4ch0m4n** [ventureoo/jabagram#6]
Eventually i have this error:

`[2024-12-09 21:15:56,210] TelegramApi - ERROR: Failed to execute the request: Cannot connect to host api.telegram.org:443 ssl:default [Connect call failed ('149.154.167.220', 443)]`

reload it and work!

Maybe it is error of my network/isp.
did you have this issue?

**Comment by ventureoo** [comment]
This is a common error when working with Telegram API, it is not fatal and bridge usually continues to work. Jabagram logs all connection issues on the Telegram side, but it has a built-in retry mechanism to resend requests within 5 attempts.
